apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: prod
  labels:
    app.kubernetes.io/name: echoserver
    app.kubernetes.io/version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: echoserver
